version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelweb
    container_name: laravelcoba
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:NVUGfCxKWYdlH7jE7IuDCc/WHye4Xet0+3gvjvaSa98=
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD:

  mysql:
    image: mysql:8.0
    container_name: mysqlweb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
